version: '3.4'

services:
  basketdb:
    image: redis:alpine

  catalogdb:
    image: mongo

  discountdb:
     image: postgres

  pgadmin:
     image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount/Discount.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
